### ISSUE TITLE
Enhance provisioning errors after 6.2.1

### ISSUE THREAD

**Issue by mendozal** [upmind-automation/provision-provider-shared-hosting#33]
After the 6.2.1 release, that affected Enhance, 

    "Remove Enhance website PHP version update API call"

I started having provisioning errors, with this result message:

`"message":"Encountered exception: InvalidArgumentException",
"provider_exception":{
"code":0,
"file":"/app/vendor/upmind/enhance-sdk/src/ObjectSerializer.php",
"line":503,
"message":"Invalid value for enum '\Upmind\EnhanceSdk\Model\ResourceName', must be one of: 'customers', 'diskspace', 'domainAliases', 'forwarders', 'ftpUsers', 'mailboxes', 'mysqlDbs', 'pageViews', 'processes', 'stagingWebsites', 'transfer', 'websites'",
"trace":[...],
"type":"InvalidArgumentException",
"validation_errors":
},`

I don't know if this has something to do with this update, or is it an API change from Enhance.

**Comment by mendozal** [comment]
This is solved.

**Comment by uphlewis** [comment]
Hi @mendozal 

Thanks for raising this issue!

The Enhance update to v9.9.0 introduced something which broke the SDK which we generated from their v9.6.0 OpenAPI spec ([upmind-automation/enhance](https://github.com/upmind-automation/enhance-sdk-php)). This has been updated now so you should no longer see any issues.

We're tweaking the config so that in future the generated SDK is more forwards-compatible with updates to Enhance in future.

Thanks,
Harry
