### ISSUE TITLE
Add support for 20i Multiple Datacentres

### ISSUE THREAD

**Issue by sdelemos** [upmind-automation/provision-provider-shared-hosting#4]
Within the 20i plans, in the assignment of customers, the IDs of the plans are generated successively.

In some examples they follow the pattern of packageid-quantity-datacenter

For this example package, its plan option if it was unlimited would be 11111-INF-uk

**Comment by uphlewis** [comment]
So I assume that just passing `11111-INF-uk` as the plan name doesn't automagically work? I can't see any reference to data centers in their API documentation

https://jsapi.apiary.io/apis/20i/reference/reseller/package-add/add-a-hosting-package.html

**Comment by uphlewis** [comment]
So really we want to add an optional `location` string to the Create function.

For now this will only be implemented in the 20i provider. Location needs to be passed to addWeb like so:
```json
{
    "type": "133416",
    "domain_name": "example-1019392347.com",
    "location": "dc_location-uk",
    "documentRoots": {
        "example-1019392347.com": "public_html"
    }
}
```

In the 20i provider we should support passing either the id such as `dc_location-uk` or the "friendly name" such as `DataCentre UK` - in order to do this we can use `GET /reseller/*/availableDcLocations` which should now return the available locations in the code:friendly name format.

If its possible to get back the 20i account's datacentre location during GetInfo then we should add an optional return data property for that too.
